"""
Cognitive Holonomy Simulation & Verification
--------------------------------------------
This script numerically validates the "Cognitive Holonomy" propositions using SymPy/NumPy.
It demonstrates that:
1. Non-zero Holonomy implies path dependence (inconsistency).
2. Minimizing Holonomy (via Lie algebra commutators) recovers path independence.
3. The relationship between Loop Holonomy and local curvature.

Author: simulai
Date: 2026-01-04
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import expm, norm
# import seaborn as sns

def random_generator(dim, scale=0.1):
    """Generate a random Lie algebra element (matrix)."""
    # For GL(n), just random matrix
    return np.random.randn(dim, dim) * scale

def parallel_transport(h, A):
    """Apply parallel transport step generated by A: h_new = exp(A) * h."""
    U = expm(A)
    return U @ h

def compute_holonomy(A_steps):
    """
    Compute holonomy along a path defined by a sequence of generators A_steps.
    Returns the total transport operator P = exp(An)...exp(A1).
    """
    P = np.eye(A_steps[0].shape[0])
    for A in A_steps:
        P = expm(A) @ P
    return P

def experiment_1_commutativity_vs_holonomy():
    """
    Proposition 2 Verification:
    Show that Holonomy H(gamma) approx ||[A, B]|| for a small loop gamma = A -> B -> -A -> -B.
    """
    print("\n--- Experiment 1: Commutativity vs Holonomy (Local Curvature) ---")
    dim = 4
    scales = np.logspace(-3, 0, 20)
    errors = []
    commutator_norms = []
    
    for s in scales:
        A = random_generator(dim, s)
        B = random_generator(dim, s)
        
        # Path 1: A then B
        P1 = expm(B) @ expm(A)
        # Path 2: B then A
        P2 = expm(A) @ expm(B)
        
        # Loop Holonomy Operator (approximate A->B->-A->-B)
        # H = P_loop - I = exp(-B)exp(-A)exp(B)exp(A) - I
        H_op = expm(-B) @ expm(-A) @ expm(B) @ expm(A)
        holonomy_measure = norm(H_op - np.eye(dim), 'fro')
        
        # Lie Algebra Commutator
        commutator = A @ B - B @ A
        commutator_norm = norm(commutator, 'fro')
        
        errors.append(holonomy_measure)
        commutator_norms.append(commutator_norm)
        
    # Plot
    plt.figure(figsize=(8, 6))
    plt.plot(commutator_norms, errors, 'o-', label='Holonomy vs Commutator')
    plt.plot([min(commutator_norms), max(commutator_norms)], 
             [min(commutator_norms), max(commutator_norms)], 'r--', label='y=x (Linear)')
    plt.xlabel('|| [A, B] || (Lie Algebra Curvature)')
    plt.ylabel('|| Holonomy - I || (Group Deviation)')
    plt.title('Validation of Proposition 1: H ~ ||F||')
    plt.legend()
    plt.grid(True)
    plt.loglog()
    plt.savefig('holonomy_validation_1.png')
    print("Experiment 1 Completed. Saved 'holonomy_validation_1.png'.")
    print(f"Sample Data (Scale={scales[-1]:.4f}): Commutator={commutator_norms[-1]:.6f}, Holonomy={errors[-1]:.6f}")

def experiment_2_path_independence():
    """
    Proposition 2 Verification:
    Show that as Holonomy -> 0, path independence is recovered.
    We generate random paths and force the algebra to be 'nearly abelian' by scaling down.
    """
    print("\n--- Experiment 2: Holonomy Minimization => Consistency ---")
    dim = 16 # High dimension embedding
    n_steps = 10
    n_trials = 100
    
    holonomies = []
    divergences = []
    
    for _ in range(n_trials):
        # Generate a set of generators that are NOT commuting initially
        generators = [random_generator(dim, scale=0.5) for _ in range(n_steps)]
        
        # Randomly permute to create two different paths with SAME set of operations (Abelian checking)
        # Path 1: Order 0, 1, 2...
        path1_gens = generators
        # Path 2: Random permutation
        path2_gens = np.random.permutation(generators)
        
        P1 = compute_holonomy(path1_gens)
        P2 = compute_holonomy(path2_gens)
        
        # Divergence between endpoints starting from same h0
        h0 = np.random.randn(dim)
        h0 /= norm(h0)
        
        h_end1 = P1 @ h0
        h_end2 = P2 @ h0
        
        divergence = norm(h_end1 - h_end2)
        
        # Holonomy measure: How non-commutative are these matrices?
        # Estimate by sum of commutators of random pairs
        comm_sum = 0
        for i in range(len(generators)):
            for j in range(i+1, len(generators)):
                comm_sum += norm(generators[i] @ generators[j] - generators[j] @ generators[i])
        
        holonomies.append(comm_sum)
        divergences.append(divergence)
        
    plt.figure(figsize=(8, 6))
    plt.scatter(holonomies, divergences, alpha=0.6)
    plt.xlabel('Total Non-Commutativity (Sum ||[Ai, Aj]||)')
    plt.ylabel('Path Divergence (||h_path1 - h_path2||)')
    plt.title('Proposition 2: Vanishing Holonomy => Path Independence')
    plt.grid(True)
    plt.savefig('holonomy_validation_2.png')
    print("Experiment 2 Completed. Saved 'holonomy_validation_2.png'.")

if __name__ == "__main__":
    np.random.seed(42)
    experiment_1_commutativity_vs_holonomy()
    experiment_2_path_independence()
